version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - /C/symfonyTest/db/conf.d:/etc/mysql/conf.d:ro
      - /C/symfonyTest/db/data:/var/lib/mysql
  php:
    build: php-fpm
    hostname: php
    container_name: php
    volumes:
      - /C/symfonyTest/app/:/var/www/symfony:rw
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - /C/symfonyTest/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /C/symfonyTest/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro